services:
  mysql:
    image: mysql:8
    container_name: babel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: babel
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./private/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:

